import json
import timeit

def read_write_json_files(input):
    # load the input json file
    with open(input_file, 'r', encoding='utf-8') as file:
        data = json.load(file)
    
    #change the size field in every record to the value 35
    for record in data:
        record['size'] = 35

if __name__ == "__main__":
    input_file = "large-file.json"

    # this line was AI generated by CHATGPT
    timed_function = lambda: read_write_json_files(input_file)

    time_taken = timeit.timeit(timed_function, number=10) / 10
    print(f'Average time taken to compute average number of vowels: {time_taken:.6f} seconds')